GET http://localhost:8080/api/shop/product/list

###
GET http://localhost:8080/api/shop/product/page/list?page=1&size=10&direction=DESC

###
GET http://localhost:8080/api/shop/product/get/bestProduct


###
GET http://localhost:8080/api/shop/product/search/list?mainCategory=MAN&subCategory=TOP&direction=DESC&page=1&size=10

###
POST http://localhost:8080/api/shop/product/upload
Content-Type: application/json

{
  "name": "필라",
  "description": "test1234",
  "price": 1000,
  "stock": 2,
  "status": "판매중",
  "mainCategory": "MAN",
  "subCategory": "PANTS",
  "img": ""
}

###
PATCH http://localhost:8080/api/shop/product/update/1
Content-Type: application/json

{
  "name": "필라",
  "description": "필라 제품",
  "price": 2000,
  "stock": 2,
  "status": "품절"
}

###
DELETE http://localhost:8080/api/shop/product/delete/1